# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftarget < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.1/tftarget_Darwin_x86_64.tar.gz"
      sha256 "7376f70b13e3bd7322b6740bde35604dd354ae0c232fbd312dfdd590199c3660"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.1/tftarget_Darwin_arm64.tar.gz"
      sha256 "b35edae180f8f85cb464072ef91ccc4862506b7983565b2e95e826f13eb34f53"

      def install
        bin.install "tftarget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.1/tftarget_Linux_x86_64.tar.gz"
      sha256 "5575d2b90c41e6392b4a62bdffd0fa7c1a467dccaacf21e878163f16e2cd1024"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.1/tftarget_Linux_arm64.tar.gz"
      sha256 "6c715802382849149fcf73461454048116cc6a2457666e19bbdcbf310b596abc"

      def install
        bin.install "tftarget"
      end
    end
  end
end
