# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tftarget < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.4/tftarget_Darwin_arm64.tar.gz"
      sha256 "790b80e45c75d5defd7a053fe53ac2a23f5cfe99259c1cfa22b0722f926b3ce6"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.4/tftarget_Darwin_x86_64.tar.gz"
      sha256 "edbca9e1ff8851f45897e224786d180c05f9234ca27594d1067ac80b18602168"

      def install
        bin.install "tftarget"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.4/tftarget_Linux_x86_64.tar.gz"
      sha256 "d8d0abaa7526c51e09960882d676e109f1783f25bc5c65dd85d5bb68172fd9fa"

      def install
        bin.install "tftarget"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/future-architect/tftarget/releases/download/v0.0.4/tftarget_Linux_arm64.tar.gz"
      sha256 "d1ef37a4c07dd7903d374ba7d4ed90e89a2dc2b0b094f1e119562df9467eda75"

      def install
        bin.install "tftarget"
      end
    end
  end
end
